language: minimal

before_install:
- openssl aes-256-cbc -K $encrypted_6f9ca22edc20_key -iv $encrypted_6f9ca22edc20_iv
  -in ./.travis/id_rsa.pem.enc -out ./.travis/id_rsa.pem -d
- chmod u=r,go= ./.travis/id_rsa.pem

script: ./.travis/script.sh
