---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: News articles
  create: documents
  templates:
  - article
- type: directory
  path: _events
  label: Events
  create: documents
  match: "**/*"
  templates:
  - event
- type: directory
  path: _results
  label: Results
  create: documents
  match: "**/*"
  templates:
  - results
- type: directory
  path: _gallery
  label: Gallery
  create: documents
  match: "**/*"
  templates:
  - gallery
- type: directory
  path: _videos
  label: Videos
  create: documents
  match: "**/*"
  templates:
  - videos
- type: directory
  path: _venues
  label: Venues
  create: documents
  match: "**/*"
  templates:
  - venue
- type: directory
  path: _sponsors
  label: Sponsors
  create: documents
  match: "**/*"
  templates:
  - sponsor
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - page
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
