name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/main
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: ${{ github.workspace }}/_site
    - name: Clear out gh-pages branch repo
      run: |
          cd ${{ github.workspace }}/_site
          git rm -f -r ./
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}/main:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest \
        /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future --baseurl ''"
    - name: Commit to gh-pages
      run: |
          cd ${{ github.workspace }}/_site
          touch .nojekyll
          git add .
          git commit -m "Auto-commit after build"
          git push